language: go
go:
- 1.8

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

install:
  - glide install

script:
  - go test $(glide novendor)
  - go build
