kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb2-replica
spec:
  type: LoadBalancer
  selector:
    app: couchdb2-replica-node
  ports:
    - port: 5984
      name: couchdb
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb2-replica-admin
spec:
  selector:
    app: couchdb2-replica-node
  ports:
    - port: 5984
      name: couchdb
    - port: 5986
      name: backdoor
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: couch
spec:
  replicas: 3
  serviceName: couchdb2-replica-admin
  template:
    metadata:
      labels:
        app: couchdb2-replica-node
    spec:
      containers:
        - name: couchdb2
          image: klaemo/couchdb:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: couchdb
              containerPort: 5984
            - name: backdoor
              containerPort: 5986
            - name: epmd
              containerPort: 4396
            - containerPort: 9100
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-admin-credentials
                  key: username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: couchdb-admin-credentials
                    key: password
            - name: ERL_FLAGS
              value: "-setcookie cabifycouchdbreplica -name couchdb@$(NAME).couchdb2-replica-admin"
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: data-dir
  volumeClaimTemplates:
    - metadata:
        name: data-dir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        # storageClassName: slow
